name: money_manager
version: 2.1.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  encrypt: ^5.0.1
  file_picker: ^4.5.1
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  flutter_rounded_date_picker: ^2.0.2
  flutter_speed_dial: ^5.1.0
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  get: ^4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  drift: ^1.5.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  share_plus: ^4.0.4
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.6
  flutter_test:
    sdk: flutter
  drift_dev: ^1.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Thin.ttf
